AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation stack.
 
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3textractPolly
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - polly:*
                  - textract:*
                Resource: "*"
 
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TextractPolly
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
 
          def lambda_handler(event, context):
              body = json.loads(event['body'])
              s3_client = boto3.client('s3')
              textract_client = boto3.client('textract')
              polly_client = boto3.client('polly')
              input_bucket_name = body['input_bucket']
              document_key = body['input_bucket_file']
              output_bucket_name = 'output-polly-jahnavi'
              response = textract_client.start_document_text_detection(
                DocumentLocation={'S3Object': {'Bucket': input_bucket_name, 'Name': document_key}}
                )
              job_status = 'IN_PROGRESS'
              while job_status == 'IN_PROGRESS':
                  result = textract_client.get_document_text_detection(JobId=response['JobId'])
                  job_status = result['JobStatus']

              extracted_text = " ".join([block['Text'] for block in result['Blocks'] if block['BlockType'] == 'LINE'])
              polly_response = polly_client.start_speech_synthesis_task(
              OutputS3BucketName=output_bucket_name,
              OutputFormat='mp3',
              Text=extracted_text,
              VoiceId='Joanna'
              )
              return {
                'statusCode': 200,
                'body': f"Text extracted and speech synthesis started with TaskId {polly_response['SynthesisTask']['TaskId']}"
                }
              
      Runtime: python3.8
      Timeout: 500
 
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyApiGateway
 
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: translate
      RestApiId: !Ref ApiGatewayRestApi
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn
 
  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApiGatewayLogsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource: "*"

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApiGatewayRestApi
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200
 
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: prod
 
  LambdaPermissionForApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*"